AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: insert-resource
    Description: Creates new resources and persists in DynamoDB
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/BIBSYSDEV/insert-resource
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/BIBSYSDEV/insert-resource

Parameters:
  ResourceTable:
    Type: String
    Description: Reference to table containing resource data


Resources:

  InsertResource:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./insert_resource
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
          REGION: !Ref AWS::Region
