AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowCredentials: true
      AllowOrigin: !Sub
        - "'${Domain}'"
        - Domain: !Ref  CorsOrigin
      AllowMethods: "'OPTIONS, GET, PUT'"
      AllowHeaders: !Ref CorsAllowHeaders

Parameters:
  ResourceTable:
    Type: String
    Description: Reference to table containing resource data
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
  CorsOrigin:
    Type: String
    Description: Value to use for Cors 'Allow...' header if value is set
    Default: '{{resolve:secretsmanager:DefaultCorsOrigin:SecretString}}'
  CorsAllowHeaders:
    Type: String
    Description: String of headers to allow.
    Default: '{{resolve:ssm:defaultCorsAllowHeaders:1}}'

Resources:
  InsertResourceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoAuthorizerArn
      Cors:
        AllowMethods: "'OPTIONS,POST'"

  InsertResource:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./insert_resource
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Auth:
              Authorizer: MyCognitoAuthorizer
            Path: /
            Method: POST
            RestApiId: !Ref InsertResourceApi
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
          REGION: !Ref AWS::Region
          ALLOWED_ORIGIN: !Ref CorsOrigin
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResourceTable

  InsertResourceBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref InsertResourceApi
      Stage: !Ref InsertResourceApi.Stage
